### ISSUE TITLE
Feature suggestion: Add support for wildcards in exclusions file

### ISSUE THREAD

**Issue by dannyvv** [asklar/unbroken#7]
Many repo's these days have multiple packages in one repo, and therefore many `node_modules` directories throughout the repo. Having to list them all individually in the config file can be cumbersome adding
```
!**\node_modules
```
would be nice. 

The workaround is to run `unbroken` before restoring packages in the CI or running `git -clean -xdf` before running locally :)

**Comment by asklar** [comment]
@dannyvv good idea. Do you know of any npm packages we can use to do this matching?
